version: "3.8"
services:
  database:
    image: mongo:6.0
    container_name: cms-mongodb.dev
    restart: always
    ports:
      - 27027:27017
    volumes:
      - mongodb:/data/db
    env_file:
      - ./../../apps/server/.env.dev

  server:
    container_name: cms-server.dev
    image: cms/server:dev
    build:
      context: ./../../
      dockerfile: server.Dockerfile
    ports:
      - 5050:5000
    depends_on:
      - database
    env_file:
      - ./../../apps/server/.env.dev

volumes:
  mongodb:
