version: "3.8"
services:
  database:
    image: mongo:6.0
    container_name: cms-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    env_file:
      - ./../apps/server/.env.production

  server:
    container_name: cms-server
    image: cms/server
    build:
      context: ./../
      dockerfile: server.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - ./../apps/server/.env.production

  client:
    container_name: cms-client
    image: cms/client
    build:
      context: ./../
      dockerfile: client.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.production
    depends_on:
      - server
      - database

volumes:
  mongodb:
